apiVersion: v1
kind: DeploymentConfig
metadata:
  name: basic-website
spec:
  replicas: 1
  selector:
    name: basic-website
  template:
    metadata:
    labels:
      app: basic-website
    spec:
      containers:
        - name: basic-website
          image: openshift/basic-website
          ports:
            - containerPort: 8080
  strategy:
    type: Rolling 
  